### ISSUE TITLE
Drawing throws error when no edges are present

### ISSUE THREAD

**Issue by MrJake222** [pweglik/badania-operacyjne#6]
When no edges are present in the graph [this line](https://github.com/pweglik/badania-operacyjne/blob/84f9f5e65655218f01e22cc1f5a0bf2b0a757859/src/show_graph.py#L40) throws:
```
ValueError: max() arg is an empty sequence
```

Genotype was 1 line with 1 stop.

**Comment by pweglik** [comment]
Solved?
